### ISSUE TITLE
phastaio_time ifdef is broken

### ISSUE THREAD

**Issue by cwsmith** [PHASTA/phastaChef#30]
Below is the output from a build of https://github.com/yangf4/phastaChef with the `phastaChef_mesh_measure` branch of `SCOREC/core`.  The same error appears with `PHASTA/phastaChef` and the `master` branch of `SCOREC/core`.
```
[  0%] Building CXX object phasta/phSolver/common/CMakeFiles/common.dir/phio_stream.cc.o
cd /users/fang/phastaChef-develop/phastaChef-Fan/build/phasta/phSolver/common && /usr/local/openmpi/1.10.6-gnu49-thread/bin/mpicxx  -DLINUX -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1 -DPARALLEL -I/users/fang/phastaChef-develop/phastaChef-Fan/build/phasta -I/users/fang/git_phasta-dev-CMake/phasta/phastaIO -I/users/fang/git_phasta-dev-CMake/phasta/shapeFunction/src -I/users/fang/git_phasta-dev-CMake/phasta/phSolver/common -I/users/fang/phastaChef-develop/phastaChef-Fan/build/phasta/phSolver/modules -I/usr/local/openmpi/1.10.6-gnu49-thread/include -I/usr/local/openmpi/1.10.6-gnu49-thread/lib -isystem /users/fang/scorec.develop/build-branch-phastaChef_mesh_measure/install/include -isystem /projects/tools/SimmetrixTest/11.0-171006/include  -Wextra -pedantic -g -O2 -fno-omit-frame-pointer   -o CMakeFiles/common.dir/phio_stream.cc.o -c /users/fang/git_phasta-dev-CMake/phasta/phSolver/common/phio_stream.cc

In file included from /users/fang/git_phasta-dev-CMake/phasta/phSolver/common/phio_stream.cc:5:0:
/users/fang/scorec.develop/build-branch-phastaChef_mesh_measure/install/include/phiotimer.h:68:20: error: variable or field 'phastaio_time' declared void
 void phastaio_time(phastaioTime* t);
```

**Comment by cwsmith** [comment]
reproduced on catan with:
PHASTA/phasta 06d45c3 (master)
SCOREC/core e66ef89 (develop)
PHASTA/phastaChef 478cedc (master)

**Comment by cwsmith** [comment]
The flags/decisions set [here](https://github.com/SCOREC/core/commit/9a659829485dea3d91a5b5d79b9f4630f0d08b6c) are not making it up to phastachef.  Probably need to use this cmake's `target_compile_definitions`:
https://cmake.org/cmake/help/v3.10/command/target_compile_definitions.html

**Comment by yangf4** [comment]
I just pushed my latest code to the GitHub. Please re-try with:
https://github.com/SCOREC/core `phastaChef_mesh_measure` branch
https://github.com/yangf4/phastaChef `master` branch
https://github.com/SCOREC/phasta `auto_mesh_adapt` branch

**Comment by cwsmith** [comment]
fixed https://github.com/SCOREC/core/commit/efe6e59dfccb37d65b1adb72c5f7507633547818

**Comment by cwsmith** [comment]
It should be fixed now in the `develop` branch.  I also merged the change into the `phastaChef_mesh_measure` branch (from `develop`).
